### ISSUE TITLE
Create a template for Presentation Decks

### ISSUE THREAD

**Issue by henlatourrette** [100Automations/Website#392] opened 2021-07-22 00:10 UTC
### Overview
We need a template that includes the 100 Automation design colors, fonts and everything.

### Action Items

- [ ] Check the design style
- [ ] Make the template
- [ ] Review it with the team

### Resources/Instructions
figma

**Comment by henlatourrette** [comment] 2021-07-22 00:13
This would be useful for issue #345

**Comment by superbunker** [comment] 2021-11-18 03:09
duplicate of #345

**Closed as completed by superbunker** 2021-11-18 03:09 UTC
Labels: good first issue, size: missing, feature: outreach, role: design
