### ISSUE TITLE
Create automation card for Gather Data Types - Jekyll

### ISSUE THREAD

**Issue by rblaz001** [100Automations/Website#29] opened 2020-08-18 18:42 UTC
### Overview
Provide collateral for the OpenSourceAutomations.org website

### Action Items
- [ ]   Gather items
  - [x]  600 x 400 image
     - [x]  Alt image text
  - [x]  Name of automation
  - [x]  A blurb about the automation
  - [x]  Links (github, slack channel url, Testing Site, Live Site, etc.)
  - [x] Healthy project files (see resources for instructions)
     - [x]  Readme.md URL
     - [x]  contributing.md URL
     - [x]  security.md URL
     - [x]  support.md URL
- [x]  Current status of Automation
     - [ ] in use and ready to deploy
     - [x] in use and being refactored
     - [ ] ready to deploy
     - [ ] in development
     - [ ] ready for development
     - [ ] in ideation
     - [ ] abandoned
   - [ ] If status in use, what codebase can it be seen in?
 - [x] Help wanted (check all that apply)
     - [ ] needs maintenance
     - [ ] needs support for users
     - [x] needs refactoring
     - [x] needs documentation 
     - [ ] needs peer review
     - [ ] needs to be built
     - [ ] needs to be researched
     - [ ] needs takeover
     - [x] needs advice
        - [x] Advice Needed: (type short description of what you need)
- [ ] Add automation Card to website

### Resources/Instructions
See project cards on the hackforla.org website for general idea, although the format of these will be different.

**GitHub Guides for healthy repos**
- [GitHub's guide: Setting guidelines for repository contributors](https://docs.github.com/en/articles/setting-guidelines-for-repository-contributors)
- [GitHub's guide: Adding a security policy to your repository
](https://docs.github.com/en/articles/adding-a-security-policy-to-your-repository)
- [GitHub's guide: Adding support resources to your project
](https://docs.github.com/en/articles/adding-support-resources-to-your-project)

**Readme should include:**
- Overview 
  - _What kind of repetitive thing do you have to do often and what is the benefit of automating it?_
- Current State 
  - _"As-is" most likely something manual but could be partially automated_
- Future Development
  - _The “To-be” state_
- Stakeholders
  - _Impact - who benefits and how?_
- Anticipated outcomes
- Resources/Instructions
  - _How to run the automation and any packages or dependencies_ 
- Language
  - _Programming language(s)_
- Platform
  - _Where is it deployed (e.g. GitHub, Linux Command Line, Windows Command Line etc)_
- Automation triggers 
  - _What starts it? What's it responding to?
  - _Is it Time-based (Specify frequency (e.g. 1x/week)?_
  - _Is it Event-based (e.g. someone just created a new GitHub on a repo)?_
- Input required 
  - _How much manual or custom input is required?_
- Output 
  - _What's the desired result? What do we not want to see?_

**Comment by rblaz001** [comment] 2020-08-18 23:25
I'm considering renaming the script and repo to Gather Data Types. I designed a logo for Gather Data Types in case I move forward with this decision. 

![Gather Data Types](https://user-images.githubusercontent.com/35281980/90574997-3e3c9a80-e16f-11ea-900f-6651de397c78.png)

**Comment by ExperimentsInHonesty** [comment] 2020-08-24 21:21
@rblaz001 lets talk about blurb, I feel like we could say more.  Let's work on it together.  How about coming 15 min early to sunday meeting.

**Comment by rblaz001** [comment] 2020-08-24 23:28
> @rblaz001 lets talk about blurb, I feel like we could say more. Let's work on it together. How about coming 15 min early to sunday meeting.

Yeah I agree with you, I'll come up with some ideas in the meantime that might better represent the project and I will show up 15 minutes earlier to our Sunday meeting so we can go over them.

**Comment by ExperimentsInHonesty** [comment] 2020-08-30 19:37
![Screen Shot 2020-08-30 at 12 32 10 PM](https://user-images.githubusercontent.com/37763229/91668001-92277780-eabd-11ea-893a-a7061a7cb520.png)

**Comment by rblaz001** [comment] 2020-08-30 19:39
Updated blurb:

When using Github and Jekyll it is easy to end up with files that are missing data types, with no built in way to enforce uniformity.  The Jekyll-Gather-Data-Types automation creates reports that identify what data types are being used across all files in a collection and what might be missing from individual files in order to target code for remediation.   Future functionality could include  providing the option of using GitHub actions to prevent incomplete files from being committed (PRs).

**Comment by ExperimentsInHonesty** [comment] 2020-08-30 19:46
https://docs.github.com/en/articles/setting-guidelines-for-repository-contributors
https://docs.github.com/en/articles/adding-a-security-policy-to-your-repository
https://docs.github.com/en/articles/adding-support-resources-to-your-project

**Comment by ExperimentsInHonesty** [comment] 2020-09-03 03:16
@rblaz001 We added some additional requirements, so I am doing a recap her of what we still need for your automation.

- [ ] Advice Needed: (type in short description of what you need)
- [ ] Healthy project files (see links for instructions)
   - [ ]  contributing.md URL see [GitHub's guide: Setting guidelines for repository contributors](https://docs.github.com/en/articles/setting-guidelines-for-repository-contributors)
   - [ ]  security.md URL see [GitHub's guide: Adding a security policy to your repository
](https://docs.github.com/en/articles/adding-a-security-policy-to-your-repository)
   - [ ]  support.md URL see [GitHub's guide: Adding support resources to your project
](https://docs.github.com/en/articles/adding-support-resources-to-your-project)

**Comment by rblaz001** [comment] 2020-09-06 16:32
Advice Needed:
I would like some advice on how to set up a proper testing suite for my automation. We need to make sure that we can validate that my automation is working as intended.

I would also like some UX advice for setting up a command line interface with menus. The current version of the script only uses flags but I am considering the use of a simple command line menu system in order to simplify user experience.

**Comment by rblaz001** [comment] 2020-09-06 16:43
README requires updating to adhere to new requirements

**Comment by ExperimentsInHonesty** [comment] 2020-09-10 04:07
@rblaz001 when you say 

> I would also like some UX advice for setting up a command line interface with menus. The current version of the script only uses flags but I am considering the use of a simple command line menu system in order to simplify user experience.

Do you want a mockup? or some other kind of UX advice?  Please specify.

**Comment by ExperimentsInHonesty** [comment] 2020-09-10 04:31
@rblaz001 

You could also check what Kian has written for his SUPPORT.md file https://github.com/100Automations/true-github-contributors/blob/mixin/SUPPORT.md. 

We put a link in there for people to join the slack for 100Automations if they have support questions the readme doesn't answer.

**Comment by rblaz001** [comment] 2020-09-12 20:18
Updated  the SUPPORT.md file as requested and removed the UX advice requested. As discussed last Sunday the command line menu is low priority so it is to early to ask for that advice.

**Comment by NivenPrasad** [comment] 2020-10-16 15:09
Hi @rblaz001, we are mocking up the automation info for the website - what programming language(s) is/are associated with your automation?

**Comment by rblaz001** [comment] 2020-10-16 16:42
@NivenPrasad The script is written in 100% Python and the data it processes is in YAML.

**Comment by NivenPrasad** [comment] 2020-12-05 23:16
@ExperimentsInHonesty will create the sample markdown file.

**Comment by ExperimentsInHonesty** [comment] 2020-12-10 03:14
WIP - still needs the following
- [ ] author info
- [ ] identification #
- [ ] details about card image size (for wiki)
- [ ] discuss rollover with team
- [ ] discuss status with team and camilla specifically re the chips and where they are represented on the figma
- [ ] discuss with team lock icon for as seen on.
---
# 'identification' is the 9 digit ID for your repo in the GitHub API.
identification: ''

title: Jekyll Gather Data Types
description: When using Github and Jekyll it is easy to end up with files that are missing data types, with no built in way to enforce uniformity. The Jekyll-Gather-Data-Types automation creates reports that identify what data types are being used across all files in a collection and what might be missing from individual files in order to target code for remediation. Future functionality could include providing the option of using GitHub actions to prevent incomplete files from being committed (PRs).

# card image should be 600px wide x 400px high
image: /assets/images/projects/[project repo name + .jpg or .png]
alt: 'Jekyll logo with test tube and words Gather Data Types all in green'

# hero image should be 1500px wide x 700px high
# image-hero: /assets/images/projects/[project repo name + -hero + .jpg or .png]
# alt-hero: 'description of the hero image'

Authors:
- name: First Last
    links:
      slack: 'https://app.slack.com/team/xxxxxx'
      github: 'https://github.com/githubusername'
    picture: https://avatars.githubusercontent.com/githubusername

links: 
  - name: Github
    url: 'https://github.com/100Automations/jekyll-gather-data-types'
  - name: Readme
    url: 'https://github.com/100Automations/jekyll-gather-data-types/blob/master/README.md'
  - name: Contributing
    url: 'https://github.com/100Automations/jekyll-gather-data-types/blob/master/contributing.md'
  - name: Support
    url: 'https://github.com/100Automations/jekyll-gather-data-types/blob/master/SUPPORT.md'
  - name: Security
    url: 'https://github.com/100Automations/jekyll-gather-data-types/blob/master/SECURITY.md'
  # unused links can be commented out
  # - name: Showcase deck
  #   url: ''
  #   alt: ''

looking:
  - category: Development
     skill: Refactoring
  - category: QA
     skill: Testing
     rollover: I would like some advice on how to set up a proper testing suite for my automation. We need to make sure that we can validate that jekyll-gather-data-types is working as intended.
  - category: Development
     skill: Documentation

needs: 
#  - maintenance
#  - support for users
  - refactoring
  - documentation
#  - peer review
#  - to be built
#  - to be researched
#  - takeover
  - advice

status:
#  - in use and ready to deploy
#  -  in use and being refactored
  - in use and needs further development (tell Camilla to add that status to the green here in [figma](https://www.figma.com/file/zGyhV8Z6sLohatYAnFoxQm/100Automations-Project-Board?node-id=175%3A2492))
#  -  ready to deploy
#  -  in development
#  -  ready for development
#  - in ideation
#  - abandoned

seen-in:
 - lock-icon

# If the card should not be included on the site, change visible to "false"
visible: true
# If the project should not have a project homepage for any given reason, add the following line (uncommented):
# project-homepage: false

---

**Comment by NivenPrasad** [comment] 2020-12-17 01:30
@ExperimentsInHonesty will make a file in the repository and update the Wiki with details about the template.

**Comment by Olivia-Chiong** [comment] 2020-12-19 22:42
@amyflo will remove spaces and do another commit.

**Comment by Olivia-Chiong** [comment] 2020-12-26 22:18
Progress: None
Blockers: ?
Availability: ?
ETA: ?

@amyflo are you able to please provide an update for this?

**Comment by henlatourrette** [comment] 2021-09-18 18:12
This one looks to be already up and running:

![image](https://user-images.githubusercontent.com/21250505/133898416-48d1c882-8c6b-46f2-9ea7-68f073e64885.png)

**Comment by superbunker** [comment] 2021-09-18 21:10
it totally exists

**Closed by superbunker** 2021-09-18 21:10 UTC
Labels: documentation, good first issue, role: back end, p-feature: automations, size: missing
