### ISSUE TITLE
Dockerise the 100 automations website

### ISSUE THREAD

**Issue by Olivia-Chiong** [100Automations/Website#103] opened 2020-12-31 01:00 UTC
### Overview
Dockerise the 100 automations website to prepare for web development.

### Action Items
- [x] Install Docker on the repo
- [x] Website should be 100automations.org
- [x] Test forking the repo as if you are a new developer. Confirm it works using instructions from Hack for LA website.

### Resources/Instructions
https://github.com/100Automations/Website
https://github.com/hackforla/website/blob/gh-pages/README.md

**Comment by Olivia-Chiong** [comment] 2021-01-02 22:05
@mdothman will find someone in #ops to review the PR and once approved, we will merge.

**Comment by akibrhast** [comment] 2021-03-03 20:13
@Olivia-Chiong Why is this issue still open? Given that the docker pull request made my @mdothman has already been merged.
https://github.com/100Automations/Website/pull/113

**Comment by Olivia-Chiong** [comment] 2021-03-03 20:32
@NivenPrasad do you know why Dean was unassigned from this and this was put in the Prioritized Backlog?

**Comment by akibrhast** [comment] 2021-03-03 20:39
My 2-cents of guess is because the original pull request made by @mdothman was closed since that was a duplicate it also never linked to this issue to being with. The dockerization that was merged however also did not link to this issue. Thus this was never closed even though the pull request was merged.

Duplicate: #108 Closed
#113 Pull request that dockerized this repo/site but did not link to this issue

![image](https://user-images.githubusercontent.com/32349001/109869118-7b153e00-7c36-11eb-82ca-14aef420a034.png)
![image](https://user-images.githubusercontent.com/32349001/109869208-97b17600-7c36-11eb-8906-14ec2408ad1c.png)

**Comment by Olivia-Chiong** [comment] 2021-03-04 00:13
@akibrhast it's not closed cos because no developer has confirmed the 3rd action step in the issue instructions has been done.

- [x] Test forking the repo as if you are a new developer. Confirm it works using instructions from Hack for LA website.

If you can confirm, we can complete the action item and close this issue.

**Comment by akibrhast** [comment] 2021-03-04 00:31
Confirmed. Made a pull request as well!

**Closed** 2021-03-04 01:36 UTC
Labels: good first issue, role: back end
