### ISSUE TITLE
Project Card Anatomy

### ISSUE THREAD

**Issue by Olivia-Chiong** [100Automations/Website#128] opened 2021-01-20 01:17 UTC
### Overview
Create a guide for the project card anatomy so it can be clear for users.

### Action Items
Create a guide for the project card anatomy with screenshots and explanation.

### Resources/Instructions
[Figma ](https://www.figma.com/file/zGyhV8Z6sLohatYAnFoxQm/100Automations-Project-Board?node-id=248%3A7443)

**Comment by superbunker** [comment] 2021-03-11 00:01
Confirming this is a full list of all the body parts of the card (with a few questions):
- Needs Help (list options?)
- Project Image
- Status (list options?)
- Languages/Frameworks
- Title
- Project Description (word count?)
- ReadMe file
- "As seen on/Used by"

**Comment by Olivia-Chiong** [comment] 2021-03-11 08:40
@superbunker yes, that looks accurate and yes, I think we should list the options.

**Comment by superbunker** [comment] 2021-03-13 21:50
Still working on the graphic for this. Should have it by wednesday.

**Comment by superbunker** [comment] 2021-03-18 02:38
Progress made, but I had some delays — bird got caught in the chimney, it escaped... into a house full of cats
ETA: post draft before Saturday (baring further wildlife interruptions)

also: noting issue #31 as reference to the various statuses on the card

**Comment by superbunker** [comment] 2021-03-20 20:22
Draft of the card anatomy image: 

![project_card_anatomy-0320_1319](https://user-images.githubusercontent.com/47950704/111884493-318b5980-897f-11eb-8f70-d675115d75af.png)

**Comment by superbunker** [comment] 2021-03-24 23:25
Sorry -- busy week. 
Will have text and draft guide by Saturday

**Comment by superbunker** [comment] 2021-03-27 20:39
A draft of the text. Enclosed below. Could use some suggestions on what further to say for some of the seemingly self-explanitory items:


> ## Project Image
> A unique image to identify and describe the project
> link: good image guide
> 
> ## Help Needed status
> If the project needs a specific type of assistance, it will be listed here
> 
> ## Languages and frameworks Used
> A list of the technologies used to create the project, and the skills that could be useful for contributors
> 
> ## Status of Project
> The stage of the project's development
> 
> ## Name of Project
> What the project is called
> 
> ## Description
> A brief overview of the project, what it does, what problem it tries to address, and how it solves it.
> 
> ## Github ReadMe Link
> This goes the "readme" file at the GitHub code hosting platform. The readme provides a more in-depth description of the automation, with an overview of the technical details.
> 
> ## Codebases project is used by
> These or projects and organizations that are currently using the automation, identified by logo
> 

Created branch with a draft guide:
https://github.com/100Automations/Website/blob/superbunker-project-card-anatomy/_guides/project-card-anatomy

Is there an example of how we handle image hosting with the guides and where images should go?

**Comment by superbunker** [comment] 2021-03-27 22:59
Will add lists of statuses to Help and Project Status, with explanations (eg: "refactoring") 

Images for guides go in the Assets folder, probably in a new folder, with images named according to the guide.

**Comment by superbunker** [comment] 2021-03-31 23:24
Revised with listed help and development statuses:


## Project Image
A [unique image](https://github.com/100Automations/Website/blob/gh-pages/_guides/creating-good-readmes-for-automations.md) to identify and describe the project
link: good image guide

## Help Needed status
If the project needs a specific type of assistance, it will be listed here
 - Needs Maintenance
 - Needs Support For Users
 - Needs Refactoring
 - Needs Documentation
 - Needs Peer Review
 - Needs To Be Built
 - Needs To Be Researched
 - Needs Advice
 - Needs Takeover
 - Advice Needed

## Languages and frameworks Used
A list of the technologies used to create the project, and the skills that could be useful for contributors

## Status of Project
The stage of the project's development
 - In Use And Ready To Deploy
 - In Use And Being Refactored
 - Ready To Deploy
 - In Development
 - Ready For Development
 - In Ideation
 - Abandoned

## Name of Project

## Description
A brief overview of the project, what it does, what problem it tries to address, and how it solves it.

## Github ReadMe Link
This goes the "readme" file at the GitHub code hosting platform. The readme provides a more in-depth description of the automation, with an overview of the technical details.

## Codebases project is used by
These or projects and organizations that are currently using the automation, identified by logo

**Comment by superbunker** [comment] 2021-04-03 21:06
In progress, working on guide

**Comment by superbunker** [comment] 2021-04-07 23:17
I noticed this wiki page in futureautomations:
https://github.com/100Automations/futureautomations/wiki/Automation-Anatomy

Would this be a duplicate of the guide?

**Comment by Olivia-Chiong** [comment] 2021-04-07 23:34
No, this was the holding page when we were doing the website flow mock up.
When the guide is done we probably copy it to the Wiki to have it there as
well.

**Comment by superbunker** [comment] 2021-04-08 05:47
Created /guides/ directory inside the /assets/images/
Uploaded the most recent project card image
Created guide (pr #245)

**Closed** 2021-04-13 00:06 UTC
Labels: feature: guides, role: product, role: project management
